[window]
opacity = 0.97

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
# family = "CaskaydiaCove Nerd Fondt"
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.bold]
# family = "CaskaydiaCove Nerd Font"
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font"
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "CaskaydiaCove Nerd Font"
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

